name: yaru_window
sdkPath: .fvm/flutter_sdk

packages:
  - packages/**

command:
  bootstrap:
    environment:
      sdk: '>=3.1.0 <4.0.0'
      flutter: '>=3.32.0'

    dev_dependencies:
      ubuntu_lints: ^0.4.1+1

scripts:
  # analyze all packages
  analyze: >
    melos exec -c 1 -- \
      flutter analyze --fatal-infos .

  # collect coverage information for all packages
  coverage: >
    melos exec -c 1 --fail-fast --dir-exists=test --ignore='*builder*' -- \
      flutter test --coverage && melos run coverage:cleanup

  # cleanup generated files from coverage
  coverage:cleanup: >
    melos exec --file-exists=coverage/lcov.info -- \
      lcov --remove coverage/lcov.info \
        '**/*.g.dart' \
        --ignore-errors unused \
        -o coverage/lcov.info


  # format all packages
  format:exclude: >
    find . -name '*.dart' \
      ! -name '*.g.dart' \
      ! -path '*/.*/*' \
      | xargs dart format --set-exit-if-changed

  # runs "flutter pub <arg(s)>" in all packages
  pub: melos exec -c 1 -- flutter pub "$@"

  # run tests in all packages
  test: >
    melos exec -c 1 --fail-fast --dir-exists=test -- \
      flutter test
