name: PR

on: [pull_request_target]

permissions:
  pull-requests: read

jobs:
  cla:
    runs-on: ubuntu-latest
    steps:
      - name: Check if CLA signed
        uses: canonical/has-signed-canonical-cla@v1
        with:
          exempted-bots: github-actions,renovate

  title:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        id: semantic-pr
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - uses: marocchino/sticky-pull-request-comment@v2
        if: always() && steps.semantic-pr.outputs.error_message != null
        with:
          header: semantic-pr-error
          message: ${{steps.semantic-pr.outputs.error_message}}
      - if: steps.semantic-pr.outputs.error_message == null
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: semantic-pr-error
          delete: true
